/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutTeamIndexRouteImport } from './routes/_layout/team/index'
import { Route as LayoutSettingsIndexRouteImport } from './routes/_layout/settings/index'
import { Route as LayoutProjectsIndexRouteImport } from './routes/_layout/projects/index'
import { Route as LayoutLocationIndexRouteImport } from './routes/_layout/location/index'
import { Route as LayoutExpensesIndexRouteImport } from './routes/_layout/expenses/index'
import { Route as LayoutDistributionIndexRouteImport } from './routes/_layout/distribution/index'
import { Route as LayoutDashboardIndexRouteImport } from './routes/_layout/dashboard/index'
import { Route as LayoutTeamAddUserRouteImport } from './routes/_layout/team/add-user'
import { Route as LayoutProjectsDetailsRouteImport } from './routes/_layout/projects/details'
import { Route as LayoutProjectsAddProjectRouteImport } from './routes/_layout/projects/add-project'
import { Route as LayoutTeamIdIndexRouteImport } from './routes/_layout/team/$id/index'
import { Route as LayoutProjectsProject_idUsersRouteImport } from './routes/_layout/projects/$project_id/users'
import { Route as LayoutTeamIdEditUserIndexRouteImport } from './routes/_layout/team/$id/edit-user/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutTeamIndexRoute = LayoutTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsIndexRoute = LayoutSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsIndexRoute = LayoutProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLocationIndexRoute = LayoutLocationIndexRouteImport.update({
  id: '/location/',
  path: '/location/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExpensesIndexRoute = LayoutExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDistributionIndexRoute = LayoutDistributionIndexRouteImport.update({
  id: '/distribution/',
  path: '/distribution/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDashboardIndexRoute = LayoutDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamAddUserRoute = LayoutTeamAddUserRouteImport.update({
  id: '/team/add-user',
  path: '/team/add-user',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsDetailsRoute = LayoutProjectsDetailsRouteImport.update({
  id: '/projects/details',
  path: '/projects/details',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsAddProjectRoute =
  LayoutProjectsAddProjectRouteImport.update({
    id: '/projects/add-project',
    path: '/projects/add-project',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTeamIdIndexRoute = LayoutTeamIdIndexRouteImport.update({
  id: '/team/$id/',
  path: '/team/$id/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProjectsProject_idUsersRoute =
  LayoutProjectsProject_idUsersRouteImport.update({
    id: '/projects/$project_id/users',
    path: '/projects/$project_id/users',
    getParentRoute: () => LayoutRoute,
  } as any)
const LayoutTeamIdEditUserIndexRoute =
  LayoutTeamIdEditUserIndexRouteImport.update({
    id: '/team/$id/edit-user/',
    path: '/team/$id/edit-user/',
    getParentRoute: () => LayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/projects/add-project': typeof LayoutProjectsAddProjectRoute
  '/projects/details': typeof LayoutProjectsDetailsRoute
  '/team/add-user': typeof LayoutTeamAddUserRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/distribution': typeof LayoutDistributionIndexRoute
  '/expenses': typeof LayoutExpensesIndexRoute
  '/location': typeof LayoutLocationIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/team': typeof LayoutTeamIndexRoute
  '/projects/$project_id/users': typeof LayoutProjectsProject_idUsersRoute
  '/team/$id': typeof LayoutTeamIdIndexRoute
  '/team/$id/edit-user': typeof LayoutTeamIdEditUserIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signup': typeof SignupRoute
  '/projects/add-project': typeof LayoutProjectsAddProjectRoute
  '/projects/details': typeof LayoutProjectsDetailsRoute
  '/team/add-user': typeof LayoutTeamAddUserRoute
  '/dashboard': typeof LayoutDashboardIndexRoute
  '/distribution': typeof LayoutDistributionIndexRoute
  '/expenses': typeof LayoutExpensesIndexRoute
  '/location': typeof LayoutLocationIndexRoute
  '/projects': typeof LayoutProjectsIndexRoute
  '/settings': typeof LayoutSettingsIndexRoute
  '/team': typeof LayoutTeamIndexRoute
  '/projects/$project_id/users': typeof LayoutProjectsProject_idUsersRoute
  '/team/$id': typeof LayoutTeamIdIndexRoute
  '/team/$id/edit-user': typeof LayoutTeamIdEditUserIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/signup': typeof SignupRoute
  '/_layout/projects/add-project': typeof LayoutProjectsAddProjectRoute
  '/_layout/projects/details': typeof LayoutProjectsDetailsRoute
  '/_layout/team/add-user': typeof LayoutTeamAddUserRoute
  '/_layout/dashboard/': typeof LayoutDashboardIndexRoute
  '/_layout/distribution/': typeof LayoutDistributionIndexRoute
  '/_layout/expenses/': typeof LayoutExpensesIndexRoute
  '/_layout/location/': typeof LayoutLocationIndexRoute
  '/_layout/projects/': typeof LayoutProjectsIndexRoute
  '/_layout/settings/': typeof LayoutSettingsIndexRoute
  '/_layout/team/': typeof LayoutTeamIndexRoute
  '/_layout/projects/$project_id/users': typeof LayoutProjectsProject_idUsersRoute
  '/_layout/team/$id/': typeof LayoutTeamIdIndexRoute
  '/_layout/team/$id/edit-user/': typeof LayoutTeamIdEditUserIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signup'
    | '/projects/add-project'
    | '/projects/details'
    | '/team/add-user'
    | '/dashboard'
    | '/distribution'
    | '/expenses'
    | '/location'
    | '/projects'
    | '/settings'
    | '/team'
    | '/projects/$project_id/users'
    | '/team/$id'
    | '/team/$id/edit-user'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signup'
    | '/projects/add-project'
    | '/projects/details'
    | '/team/add-user'
    | '/dashboard'
    | '/distribution'
    | '/expenses'
    | '/location'
    | '/projects'
    | '/settings'
    | '/team'
    | '/projects/$project_id/users'
    | '/team/$id'
    | '/team/$id/edit-user'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/signup'
    | '/_layout/projects/add-project'
    | '/_layout/projects/details'
    | '/_layout/team/add-user'
    | '/_layout/dashboard/'
    | '/_layout/distribution/'
    | '/_layout/expenses/'
    | '/_layout/location/'
    | '/_layout/projects/'
    | '/_layout/settings/'
    | '/_layout/team/'
    | '/_layout/projects/$project_id/users'
    | '/_layout/team/$id/'
    | '/_layout/team/$id/edit-user/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/team/': {
      id: '/_layout/team/'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof LayoutTeamIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings/': {
      id: '/_layout/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/': {
      id: '/_layout/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof LayoutProjectsIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/location/': {
      id: '/_layout/location/'
      path: '/location'
      fullPath: '/location'
      preLoaderRoute: typeof LayoutLocationIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/expenses/': {
      id: '/_layout/expenses/'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof LayoutExpensesIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/distribution/': {
      id: '/_layout/distribution/'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof LayoutDistributionIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/dashboard/': {
      id: '/_layout/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof LayoutDashboardIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team/add-user': {
      id: '/_layout/team/add-user'
      path: '/team/add-user'
      fullPath: '/team/add-user'
      preLoaderRoute: typeof LayoutTeamAddUserRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/details': {
      id: '/_layout/projects/details'
      path: '/projects/details'
      fullPath: '/projects/details'
      preLoaderRoute: typeof LayoutProjectsDetailsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/add-project': {
      id: '/_layout/projects/add-project'
      path: '/projects/add-project'
      fullPath: '/projects/add-project'
      preLoaderRoute: typeof LayoutProjectsAddProjectRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team/$id/': {
      id: '/_layout/team/$id/'
      path: '/team/$id'
      fullPath: '/team/$id'
      preLoaderRoute: typeof LayoutTeamIdIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/projects/$project_id/users': {
      id: '/_layout/projects/$project_id/users'
      path: '/projects/$project_id/users'
      fullPath: '/projects/$project_id/users'
      preLoaderRoute: typeof LayoutProjectsProject_idUsersRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team/$id/edit-user/': {
      id: '/_layout/team/$id/edit-user/'
      path: '/team/$id/edit-user'
      fullPath: '/team/$id/edit-user'
      preLoaderRoute: typeof LayoutTeamIdEditUserIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutProjectsAddProjectRoute: typeof LayoutProjectsAddProjectRoute
  LayoutProjectsDetailsRoute: typeof LayoutProjectsDetailsRoute
  LayoutTeamAddUserRoute: typeof LayoutTeamAddUserRoute
  LayoutDashboardIndexRoute: typeof LayoutDashboardIndexRoute
  LayoutDistributionIndexRoute: typeof LayoutDistributionIndexRoute
  LayoutExpensesIndexRoute: typeof LayoutExpensesIndexRoute
  LayoutLocationIndexRoute: typeof LayoutLocationIndexRoute
  LayoutProjectsIndexRoute: typeof LayoutProjectsIndexRoute
  LayoutSettingsIndexRoute: typeof LayoutSettingsIndexRoute
  LayoutTeamIndexRoute: typeof LayoutTeamIndexRoute
  LayoutProjectsProject_idUsersRoute: typeof LayoutProjectsProject_idUsersRoute
  LayoutTeamIdIndexRoute: typeof LayoutTeamIdIndexRoute
  LayoutTeamIdEditUserIndexRoute: typeof LayoutTeamIdEditUserIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProjectsAddProjectRoute: LayoutProjectsAddProjectRoute,
  LayoutProjectsDetailsRoute: LayoutProjectsDetailsRoute,
  LayoutTeamAddUserRoute: LayoutTeamAddUserRoute,
  LayoutDashboardIndexRoute: LayoutDashboardIndexRoute,
  LayoutDistributionIndexRoute: LayoutDistributionIndexRoute,
  LayoutExpensesIndexRoute: LayoutExpensesIndexRoute,
  LayoutLocationIndexRoute: LayoutLocationIndexRoute,
  LayoutProjectsIndexRoute: LayoutProjectsIndexRoute,
  LayoutSettingsIndexRoute: LayoutSettingsIndexRoute,
  LayoutTeamIndexRoute: LayoutTeamIndexRoute,
  LayoutProjectsProject_idUsersRoute: LayoutProjectsProject_idUsersRoute,
  LayoutTeamIdIndexRoute: LayoutTeamIdIndexRoute,
  LayoutTeamIdEditUserIndexRoute: LayoutTeamIdEditUserIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
